name: test_form_tuqaatech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  dartz: ^0.10.1  
  internet_connection_checker: ^0.0.1+3
  equatable: ^2.0.3
  select_form_field: ^2.2.0 
  image_picker: ^0.8.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.1
  email_validator: ^2.1.16
  page_animation_transition: ^0.0.9
  get_it: ^7.2.0
  # animations: ^2.0.7
  # cloud_firestore: ^4.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/welcome.png
    - asset/images/bg.png
    - asset/images/start.png
    - asset/icons/image.png
    - asset/icons/email.png
    - asset/icons/key.png
    - asset/icons/point.png
